name: "Upload Docs"

description: "Build and upload docs to GitHub Pages"
inputs:
  branches:
    description: "Branches to trigger the workflow on"
    required: false
    default: "main,ci/evm-docs-to-github-pages"
  environment_name:
    description: "Name of the deployment environment"
    required: false
    default: "github-pages"
    
runs:
  using: "composite"
  steps:
    - name: Install Solidity docgen
      run: npm install -g solidity-docgen
      shell: bash

    - name: Create docs directory
      run: mkdir -p docs
      shell: bash

    - name: Build Solidity documentation
      run: npx hardhat docgen
      shell: bash

    - name: Check for generateOverviewDocs script
      id: check-generate-overview-docs
      run: |
        if [ -f "scripts/generateOverviewDocs.js" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Generate Overview Documentation if exists locally
      if: steps.check-generate-overview-docs.outputs.exists == 'true'
      run: npm run generate-overview-docs
      shell: bash

   - name: Generate Overview Documentation if exists remotely
      if: steps.check-generate-overview-docs.outputs.exists == 'false'
      run: node ${{ inputs.script }}
      shell: bash

    - name: Add YAML front matter for Jekyll
      run: |
        find docs -name '*.md' -exec sh -c 'sed -i "" "1s/^/---\nlayout: default\n---\n/" "$0"' {} \;
      shell: bash

    - name: Setup Github Pages
      uses: actions/configure-pages@v5

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
