name: "Upload Docs"

description: "Build and upload docs to GitHub Pages"
inputs:
  branches:
    description: "Branches to trigger the workflow on"
    required: false
    default: "main,ci/evm-docs-to-github-pages"
  environment_name:
    description: "Name of the deployment environment"
    required: false
    default: "github-pages"
  script:
    description: 'The script to run for generating documentation'
    required: false
    default: 'scripts/generateOverviewDocs.js'
    
runs:
  using: "composite"
  steps:
    - name: Create docs directory
      run: |
        if [ -d "docs" ]; then
          rm -rf docs
          echo "removed pre-existing 'docs' dir"
        fi
        mkdir -p docs
      shell: bash

    - name: Build Solidity documentation
      run: |
        if ! npx hardhat docgen; then
          echo "Hardhat failed to generate documentation"
          exit 1
        fi
      shell: bash

    - name: Check for generateOverviewDocs script
      id: check-generate-overview-docs
      run: |
        if [ -f "scripts/generateOverviewDocs.js" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Generate Overview Documentation if exists locally
      if: steps.check-generate-overview-docs.outputs.exists == 'true'
      run: npm run generate-overview-docs
      shell: bash

    - name: Generate Overview Documentation if exists remotely
      if: steps.check-generate-overview-docs.outputs.exists == 'false'
      run: node ${{ inputs.script }}
      shell: bash

    - name: Verify docs directory is not empty
        run: |
          if [ ! -d "docs" ] || [ -z "$(ls -A docs/index.md)" ]; then
            echo "Docs directory is empty or does not exist"
            exit 1
          fi
        shell: bash

    - name: Add YAML front matter for Jekyll
      run: |
        find docs -name '*.md' -exec sh -c 'sed -i "" "1s/^/---\nlayout: default\n---\n/" "$0"' {} \;
      shell: bash

    - name: Setup Github Pages
      uses: actions/configure-pages@v5

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
