name: Aderyn Static Analysis

on:
  pull_request:
    branches:
      - ci/aderyn-analysis
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aderyn:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Aderyn
        run: cargo install --git https://github.com/Cyfrin/aderyn.git

      - name: Upload Aderyn Report
        run: aderyn --output report.md .

      - name: Upload Aderyn Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aderyn-report
          path: report.md