name: Aderyn Static Analysis

on:
  pull_request:
    branches:
      - ci/aderyn-analysis
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aderyn:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Run Aderyn Static Analysis
        uses: ./.github/actions/aderyn
        with:
          rust_toolchain: stable
          aderyn_version: v0.3.3