name: Aderyn Static Analysis

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aderyn:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Run Aderyn Static Analysis
        uses: axelarnetwork/axelar-gmp-sdk-solidity/.github/actions/aderyn@main
