name: Aderyn Static Analysis

on:
  pull_request:
    branches:
      - ci/aderyn-analysis
      - main
  push:
    branches:
      - ci/aderyn-analysis


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aderyn:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cyfrinup and Aderyn
        run: |
          curl -L https://raw.githubusercontent.com/Cyfrin/aderyn/dev/cyfrinup/install | bash
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          source ~/.bashrc
          cyfrinup

      - name: Run Aderyn
        run: aderyn

   
