name: Publish Bytecode

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Release Tag'
        required: true

jobs:
  publish-bytecode:
    strategy:
      matrix:
        node-version:
          - 18.x
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Flatten contracts
        run: npm run flatten

      - name: Clean artifacts
        run: npm run clean:artifacts

      - name: Get release tag
        run: |
          TAG=${{ github.event.inputs.TAG || github.ref }}
          echo "release_tag=${TAG#refs/tags/}" >> "$GITHUB_ENV"

      - name: Create zip file
        working-directory: ./artifacts
        run: |
          zip -r Bytecode-${{ env.release_tag }}.zip *

      - name: Upload Bytecode to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/Bytecode-${{ env.release_tag }}.zip
          tag: ${{ env.release_tag }}
          overwrite: true
