name: Slither Static Analysis

on:
  - pull_request

jobs:
  analyze:
    strategy:
      matrix:
        node-version:
          - 18.x
        os:
          - blacksmith-2vcpu-ubuntu-2204
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
