name: Slither Static Analysis

on:
  - pull_request

jobs:
  analyze:
    strategy:
      matrix:
        node-version:
          - 18.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
